[package]
name = "ssa-cache"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bitcode = { workspace = true, optional = true }
fjall = { workspace = true, default-features = false, optional = true }
rand = { workspace = true, features = ["thread_rng"] }
rayon = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true, features = ["small_rng"] }
tempfile = { workspace = true }

[features]
default = ["bitcode", "fjall"]
bitcode = ["dep:bitcode"]
fjall = ["dep:fjall"]

[lints]
workspace = true
